services:
  # 後端服務
  - type: web
    name: ig-hashtag-backend
    env: node
    repo: https://github.com/qazasd2518995/donation.git
    buildCommand: cd backend && npm install
    startCommand: cd backend && node app.js
    envVars:
      - key: IG_TOKEN
        value: "EAAZABZBFyTPjUBO81GfrzZBLej4EhHFZAL2a996JziCFuybnEehqSKMJnee7aRcBJE0j2saqWZCQb22ydzx6ysul8dyaJ0sh6sTV0SC10PhDHh7FVqNyMkjfYAaDyOncZAPsiqX7aqhacRvKZAuJb4w5YjIvwgvy7wdSqbouJtecOkSdZBCKPuywEx51cI93qPvKkrZBdJOZBZA"
      - key: IG_USER_ID
        value: "17841474086492936"
      - key: IG_POST_ID
        value: "18079076146744868"
      - key: PORT
        value: 10000

  # 前端服務
  - type: web
    name: donation-dashboard-frontend
    env: node
    repo: https://github.com/qazasd2518995/donation.git
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: "https://ig-hashtag-backend.onrender.com" 